### ISSUE TITLE
Consistency of YAML indentation

### ISSUE THREAD

**Issue by mikesir87** [docker/awesome-compose#22]
I know it doesn't affect the functionality of the compose files, but it does affect scan-ability and might raise questions if folks see inconsistencies. One example...

```yaml
    image: postgres
    restart: always
    secrets:
    - db-password
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
      - spring-postges
```

The networks config is indented while the secrets and volumes aren't. Personally, I like indenting all lists as it makes easier to scan the keys. But, I'm fine with not indenting as long as it's consistent. I'd gladly update them and submit a PR if someone tells me which way to go.
