### ISSUE TITLE
How to start a privileged replica in swarm mode?

### ISSUE THREAD

**Issue by jeyrce** [docker/awesome-compose#278]
### compose

```
version: "3.8"

services:
  udcp_collect:
    image: hub.deepin.com/xapi:pre-amd64
    privileged: true
    volumes:
      - /opt/udcp/udcp_collect/hardware_information/:/service/data/
      - /sbin/dmidecode:/sbin/dmidecode
      - /dev/mem:/dev/mem
    command:
      - "/service/api"
    logging:
      options:
        max-size: 10m
        max-file: 3
```

### problem

The container were able to read the volume `/dev/mem` in docker-compose mode, but not worked in swarm mode like the follow log:

```
x_udcp-collect.1.9fh93hvhqa4m@uos-PC    | panic: failed to open stream: open /dev/mem: operation not permitted
```

Seems the `privileged` were not supported in swarm mode when stack deployed. So how to read special file like `/dev/mem` in swarm mode?
