### ISSUE TITLE
Add keycloak + mysql sample

### ISSUE THREAD

**Issue by bruno1pb13** [docker/awesome-compose#340]
Keycloak is a software that provides a single sign-on solution for web applications and RESTful web services. It helps developers to secure their apps and services with features like user federation, identity providers, and role management. It supports standard protocols like OAuth 2.0, OpenID Connect, and SAML 2.0. 

```yaml
version: '3'

volumes:
  mysql_data:
      driver: local

services:
  mysql_keycloak:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
        
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql_keycloak
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      ports:
        - 8080:8080
      depends_on:
        - mysql_keycloak
      command:
        start-dev -- -b 0.0.0.0

volumes:
  mysql_data:
```
