### ISSUE TITLE
Question : nginx-wsgi-flask -> compose.yaml

### ISSUE THREAD

**Issue by Foundsheep** [docker/awesome-compose#399]
Hi there,

In case someone wants to use a volume to gather logs from the services like me, could we change the script as follows and won't there be any problems, or could I just write another line in the volume section?

**/nginx/Dockerfile**
```Dockerfile
...
COPY --chown=nginx:nginx start.sh /app/start.sh
COPY --chown=nginx:nginx default.conf /tmp/default.conf  # line added
...
```

**compose.yaml**
```yaml
services:
  nginx-proxy:
    ...
    volumes:
      - <my-volume-name>:<location-to-logs>  # replaced ./nginx/default.conf:/tmp/default.conf
...
volume:
  <my-volume-name>:
```
